;METADATA=(Diff=true, UseCommands=true)
[/Script/EngineSettings.GeneralProjectSettings]
ProjectID=2C2D5DE34DC89F31CCD863B271CCD778

[/Script/UnrealEd.ProjectPackagingSettings]
+DirectoriesToAlwaysStageAsUFS=(Path="ArticyContent/Generated")
+DirectoriesToAlwaysCook=(Path="/Game/ArticyContent")

