// articy Software GmbH & Co. KG
/** This code file was generated by ArticyImporter. Changes to this file will get lost once the code is regenerated. */

#pragma once

#include "CoreUObject.h"
#include "ArticyExpressoScripts.h"
#include "NanorenoGlobalVariables.h"
#include "NanorenoExpressoScripts.generated.h"

UINTERFACE(Blueprintable)
class UNanorenoMethodsProvider : public UInterface { GENERATED_BODY() };
class INanorenoMethodsProvider
{
	GENERATED_BODY()
	
public:
	
	UFUNCTION(BlueprintCallable, BlueprintNativeEvent, Category="Articy Methods Provider", meta=(DisplayName="SetBackground"))
	bool SetBackground_String(const FString& aParam0) ;
	virtual bool SetBackground_String_Implementation(const FString& aParam0) { return true; };
	
	UFUNCTION(BlueprintCallable, BlueprintNativeEvent, Category="Articy Methods Provider", meta=(DisplayName="PlaySound"))
	bool PlaySound_String(const FString& aParam0) ;
	virtual bool PlaySound_String_Implementation(const FString& aParam0) { return true; };
};

UCLASS(BlueprintType, Blueprintable)
class NANORENO_API UNanorenoExpressoScripts : public UArticyExpressoScripts
{
	GENERATED_BODY()
	
private:
	
	bool SetBackground(const FString& aParam0) const
	{
		auto methodProvider = GetUserMethodsProviderObject();
		if(!methodProvider) return true;
		return INanorenoMethodsProvider::Execute_SetBackground_String(methodProvider, aParam0);
	}
	bool PlaySound(const FString& aParam0) const
	{
		auto methodProvider = GetUserMethodsProviderObject();
		if(!methodProvider) return true;
		return INanorenoMethodsProvider::Execute_PlaySound_String(methodProvider, aParam0);
	}
	
private:
	
	mutable TWeakObjectPtr<UNanorenoGameStateVariables> GameState = nullptr;
	mutable TWeakObjectPtr<UNanorenoGlobalVariables> ActiveGlobals = nullptr;
	
	void SetGV(UArticyGlobalVariables* GV) const override
	{
		auto gv = Cast<UNanorenoGlobalVariables>(GV);
		/** Initialize all GV namespace references (or nullify if we're setting to nullptr) */
		GameState = gv ? gv->GameState : nullptr;
		/** Store GVs */
		ActiveGlobals = gv;
	}
	
	UArticyGlobalVariables* GetGV() override
	{
		/** Return active global variables as set by SetGV */
		if(ActiveGlobals.IsValid()) { return ActiveGlobals.Get(); }
		return nullptr;
	}
	
	UClass* GetUserMethodsProviderInterface() override
	{
		return UNanorenoMethodsProvider::StaticClass();
	}
	
public:
	
	#if !((defined(PLATFORM_PS4) && PLATFORM_PS4) || (defined(PLATFORM_PS5) && PLATFORM_PS5))
	#pragma warning(push)
	#pragma warning(disable: 4883) //<disable "optimization cannot be applied due to function size" compile error.
	#endif
	 UNanorenoExpressoScripts() 
	{
		Conditions.Add(-1763144621, [&]
		{
			return ConditionOrTrue(
				SetBackground(FString(TEXT("General Store")))
			);
		});
		Conditions.Add(-778666339, [&]
		{
			return ConditionOrTrue(
				SetBackground(FString(TEXT("Apothecary")))
			);
		});
		Conditions.Add(1365931001, [&]
		{
			return ConditionOrTrue(
				SetBackground(FString(TEXT("Tailorshop")))
			);
		});
		Instructions.Add(54345062, [&]
		{
			(*GameState->LookedAroundMailbox) = true;
		});
		Instructions.Add(-2137613694, [&]
		{
			(*GameState->OpenedMailbox) = true;
		});
		Conditions.Add(-1711399687, [&]
		{
			return ConditionOrTrue(
				SetBackground(FString(TEXT("Forest")))
			);
		});
		Instructions.Add(579762233, [&]
		{
			SetBackground(FString(TEXT("Mailbox with feet")));
		});
		Instructions.Add(-2145456604, [&]
		{
			(*GameState->TookMushlingMail) = true;
		});
		Instructions.Add(453919106, [&]
		{
			(*GameState->TookMushlingMail) = false;
		});
		Conditions.Add(1055292674, [&]
		{
			return ConditionOrTrue(
				SetBackground(FString(TEXT("Lumberyard")))
			);
		});
		Conditions.Add(-405321653, [&]
		{
			return ConditionOrTrue(
				SetBackground(FString(TEXT("School")))
			);
		});
		Conditions.Add(-1638166579, [&]
		{
			return ConditionOrTrue(
				SetBackground(FString(TEXT("Town Hall")))
			);
		});
		Conditions.Add(263151215, [&]
		{
			return ConditionOrTrue(
				SetBackground(FString(TEXT("Opal's Room")))
			);
		});
		Conditions.Add(667563602, [&]
		{
			return ConditionOrTrue(
				SetBackground(FString(TEXT("Inn")))
			);
		});
		Conditions.Add(-1090126290, [&]
		{
			return ConditionOrTrue(
				PlaySound(FString(TEXT("Knock Knock")))
			);
		});
		Instructions.Add(1149983384, [&]
		{
			(*GameState->TookMushlingMail2) = true;
		});
		Conditions.Add(579762233, [&]
		{
			return ConditionOrTrue(
				SetBackground(FString(TEXT("Mailbox with feet")))
			);
		});
		Conditions.Add(1551351120, [&]
		{
			return ConditionOrTrue(
				SetBackground(FString(TEXT("Forest")))
			);
		});
		Conditions.Add(-1779323168, [&]
		{
			return ConditionOrTrue(
				SetBackground(FString(TEXT("Carpenter")))
			);
		});
		Instructions.Add(-1080852522, [&]
		{
			(*GameState->TookMushlingMail) = true;
		});
		Instructions.Add(432885390, [&]
		{
			(*GameState->TookMushlingMail3) = true;
		});
		Conditions.Add(-1914132273, [&]
		{
			return ConditionOrTrue(
				(*GameState->InquireAboutBooks) == true
			);
		});
		Conditions.Add(356762263, [&]
		{
			return ConditionOrTrue(
				(*GameState->BooksDelivered) == true
			);
		});
		Conditions.Add(-1636524287, [&]
		{
			return ConditionOrTrue(
				(*GameState->DeliverMailWOBreakfast) == true
			);
		});
		Conditions.Add(-1528146134, [&]
		{
			return ConditionOrTrue(
				(*GameState->BooksDelivered) == true && (*GameState->InquireAboutBooks) == true
			);
		});
		Conditions.Add(259470881, [&]
		{
			return ConditionOrTrue(
				(*GameState->OpenedMailbox) == true
			);
		});
		Conditions.Add(-1931701819, [&]
		{
			return ConditionOrTrue(
				(*GameState->LookedAroundMailbox) == true
			);
		});
		Conditions.Add(268386951, [&]
		{
			return ConditionOrTrue(
				(*GameState->TookMushlingMail) == true
			);
		});
		Conditions.Add(-882182597, [&]
		{
			return ConditionOrTrue(
				(*GameState->TookMushlingMail2) == true
			);
		});
		Conditions.Add(-660377917, [&]
		{
			return ConditionOrTrue(
				(*GameState->TookMushlingMail) == true
			);
		});
		Instructions.Add(-1565396723, [&]
		{
			(*GameState->BooksDelivered) = true;
		});
		Instructions.Add(784019345, [&]
		{
			(*GameState->DeliverMailWOBreakfast) = true;
		});
		Instructions.Add(34145388, [&]
		{
			(*GameState->InquireAboutBooks) = true;
		});
		Instructions.Add(632960496, [&]
		{
			PlaySound(FString(TEXT("Loud Crash from Above")));
		});
		Instructions.Add(667563602, [&]
		{
			SetBackground(FString(TEXT("Inn")));
		});
		Instructions.Add(191485815, [&]
		{
			SetBackground(FString(TEXT("Library")));
		});
		Instructions.Add(1055292674, [&]
		{
			SetBackground(FString(TEXT("Lumberyard")));
		});
		Instructions.Add(-2133513516, [&]
		{
			PlaySound(FString(TEXT("Thwack")));
		});
		Instructions.Add(1551351120, [&]
		{
			SetBackground(FString(TEXT("Forest")));
		});
		Instructions.Add(-405321653, [&]
		{
			SetBackground(FString(TEXT("School")));
		});
	}
	#if !((defined(PLATFORM_PS4) && PLATFORM_PS4) || (defined(PLATFORM_PS5) && PLATFORM_PS5))
	#pragma warning(pop)
	#endif
};
