// articy Software GmbH & Co. KG
/** This code file was generated by ArticyImporter. Changes to this file will get lost once the code is regenerated. */

#pragma once

#include "CoreUObject.h"
#include "ArticyDatabase.h"
#include "NanorenoExpressoScripts.h"
#include "NanorenoDatabase.generated.h"

UCLASS(BlueprintType)
class NANORENO_API UNanorenoDatabase : public UArticyDatabase
{
	GENERATED_BODY()
	
public:
	
	/** Get the instance (copy of the asset) of the database. */
	UFUNCTION(BlueprintPure, Category = "articy:draft", meta=(HidePin="WorldContext", DefaultToSelf="WorldContext", DisplayName="GetArticyDB", keywords="database"))
	static UNanorenoDatabase* Get(const UObject* WorldContext) 
	{
		return static_cast<UNanorenoDatabase*>(Super::Get(WorldContext));
	}
	
	/** Get the global variables. */
	UFUNCTION(BlueprintPure, Category = "articy:draft", meta=(keywords="global variables"))
	UNanorenoGlobalVariables* GetGVs() const override
	{
		return static_cast<UNanorenoGlobalVariables*>(Super::GetGVs());
	}
	/** Gets the current runtime instance of a set of GVs. */
	UFUNCTION(BlueprintPure, Category = "articy:draft", meta=(keywords="global variables"))
	UNanorenoGlobalVariables* GetRuntimeGVs(UArticyAlternativeGlobalVariables* Asset) const override
	{
		return static_cast<UNanorenoGlobalVariables*>(Super::GetRuntimeGVs(Asset));
	}
};
