// articy Software GmbH & Co. KG
/** This code file was generated by ArticyImporter. Changes to this file will get lost once the code is regenerated. */

#pragma once

#include "CoreUObject.h"
#include "ArticyExpressoScripts.h"
#include "NanorenoGlobalVariables.h"
#include "NanorenoExpressoScripts.generated.h"

UINTERFACE(Blueprintable)
class UNanorenoMethodsProvider : public UInterface { GENERATED_BODY() };
class INanorenoMethodsProvider
{
	GENERATED_BODY()
	
public:
	
	UFUNCTION(BlueprintCallable, BlueprintNativeEvent, Category="Articy Methods Provider", meta=(DisplayName="SetBackground"))
	void SetBackground_String(const FString& aParam0) ;
	virtual void SetBackground_String_Implementation(const FString& aParam0) {  };
	
	UFUNCTION(BlueprintCallable, BlueprintNativeEvent, Category="Articy Methods Provider", meta=(DisplayName="PlaySound"))
	void PlaySound_String(const FString& aParam0) ;
	virtual void PlaySound_String_Implementation(const FString& aParam0) {  };
};

UCLASS(BlueprintType, Blueprintable)
class NANORENO_API UNanorenoExpressoScripts : public UArticyExpressoScripts
{
	GENERATED_BODY()
	
private:
	
	void SetBackground(const FString& aParam0) const
	{
		auto methodProvider = GetUserMethodsProviderObject();
		if(!methodProvider) return ;
		INanorenoMethodsProvider::Execute_SetBackground_String(methodProvider, aParam0);
	}
	void PlaySound(const FString& aParam0) const
	{
		auto methodProvider = GetUserMethodsProviderObject();
		if(!methodProvider) return ;
		INanorenoMethodsProvider::Execute_PlaySound_String(methodProvider, aParam0);
	}
	
private:
	
	mutable TWeakObjectPtr<UNanorenoGameStateVariables> GameState = nullptr;
	mutable TWeakObjectPtr<UNanorenoGlobalVariables> ActiveGlobals = nullptr;
	
	void SetGV(UArticyGlobalVariables* GV) const override
	{
		auto gv = Cast<UNanorenoGlobalVariables>(GV);
		/** Initialize all GV namespace references (or nullify if we're setting to nullptr) */
		GameState = gv ? gv->GameState : nullptr;
		/** Store GVs */
		ActiveGlobals = gv;
	}
	
	UArticyGlobalVariables* GetGV() override
	{
		/** Return active global variables as set by SetGV */
		if(ActiveGlobals.IsValid()) { return ActiveGlobals.Get(); }
		return nullptr;
	}
	
	UClass* GetUserMethodsProviderInterface() override
	{
		return UNanorenoMethodsProvider::StaticClass();
	}
	
public:
	
	#if !((defined(PLATFORM_PS4) && PLATFORM_PS4) || (defined(PLATFORM_PS5) && PLATFORM_PS5))
	#pragma warning(push)
	#pragma warning(disable: 4883) //<disable "optimization cannot be applied due to function size" compile error.
	#endif
	 UNanorenoExpressoScripts() 
	{
		Instructions.Add(1149983384, [&]
		{
			(*GameState->TookMushlingMail2) = true;
		});
		Instructions.Add(-2145456604, [&]
		{
			(*GameState->TookMushlingMail) = true;
		});
		Conditions.Add(-1636524287, [&]
		{
			return ConditionOrTrue(
				(*GameState->DeliverMailWOBreakfast) == true
			);
		});
		Conditions.Add(356762263, [&]
		{
			return ConditionOrTrue(
				(*GameState->BooksDelivered) == true
			);
		});
		Conditions.Add(-1722534272, [&]
		{
			return ConditionOrTrue(
				(*GameState->InquireAboutBooks) == true
			);
		});
		Conditions.Add(1807382270, [&]
		{
			return ConditionOrTrue(
				(*GameState->BooksDelivered) == true  && (*GameState->InquireAboutBooks) == true
			);
		});
		Conditions.Add(259470881, [&]
		{
			return ConditionOrTrue(
				(*GameState->OpenedMailbox) == true
			);
		});
		Conditions.Add(-1931701819, [&]
		{
			return ConditionOrTrue(
				(*GameState->LookedAroundMailbox) == true
			);
		});
		Conditions.Add(268386951, [&]
		{
			return ConditionOrTrue(
				(*GameState->TookMushlingMail) == true
			);
		});
		Conditions.Add(-882182597, [&]
		{
			return ConditionOrTrue(
				(*GameState->TookMushlingMail2) == true
			);
		});
		Conditions.Add(-660377917, [&]
		{
			return ConditionOrTrue(
				(*GameState->TookMushlingMail) == true
			);
		});
		Instructions.Add(667563602, [&]
		{
			SetBackground(FString(TEXT("Inn")));
		});
		Instructions.Add(784019345, [&]
		{
			(*GameState->DeliverMailWOBreakfast) = true;
		});
		Instructions.Add(34145388, [&]
		{
			(*GameState->InquireAboutBooks) = true;
		});
		Instructions.Add(-1565396723, [&]
		{
			(*GameState->BooksDelivered) = true;
		});
		Instructions.Add(191485815, [&]
		{
			SetBackground(FString(TEXT("Library")));
		});
		Instructions.Add(508283933, [&]
		{
			SetBackground(FString(TEXT("GeneralStore")));
		});
		Instructions.Add(632960496, [&]
		{
			PlaySound(FString(TEXT("Loud Crash from Above")));
		});
		Instructions.Add(-778666339, [&]
		{
			SetBackground(FString(TEXT("Apothecary")));
		});
		Instructions.Add(970979305, [&]
		{
			SetBackground(FString(TEXT("Seamstress")));
		});
		Instructions.Add(1055292674, [&]
		{
			SetBackground(FString(TEXT("Lumberyard")));
		});
		Instructions.Add(-2133513516, [&]
		{
			PlaySound(FString(TEXT("Thwack")));
		});
		Instructions.Add(1551351120, [&]
		{
			SetBackground(FString(TEXT("Forest")));
		});
		Instructions.Add(-1659073513, [&]
		{
			SetBackground(FString(TEXT("MailboxWithFeet")));
		});
		Instructions.Add(54345062, [&]
		{
			(*GameState->LookedAroundMailbox) = true;
		});
		Instructions.Add(-2137613694, [&]
		{
			(*GameState->OpenedMailbox) = true;
		});
		Instructions.Add(-405321653, [&]
		{
			SetBackground(FString(TEXT("School")));
		});
		Instructions.Add(1031130970, [&]
		{
			SetBackground(FString(TEXT("TownHall")));
		});
		Instructions.Add(1719607317, [&]
		{
			SetBackground(FString(TEXT("OpalsRoom")));
		});
		Instructions.Add(-1090126290, [&]
		{
			PlaySound(FString(TEXT("Knock Knock")));
		});
		Instructions.Add(-1616562767, [&]
		{
			SetBackground(FString(TEXT("GeneralStore")));
		});
		Instructions.Add(-1779323168, [&]
		{
			SetBackground(FString(TEXT("Carpenter")));
		});
		Instructions.Add(432885390, [&]
		{
			(*GameState->TookMushlingMail3) = true;
		});
		Instructions.Add(-1080852522, [&]
		{
			(*GameState->TookMushlingMail) = true;
		});
	}
	#if !((defined(PLATFORM_PS4) && PLATFORM_PS4) || (defined(PLATFORM_PS5) && PLATFORM_PS5))
	#pragma warning(pop)
	#endif
};
