// articy Software GmbH & Co. KG
/** This code file was generated by ArticyImporter. Changes to this file will get lost once the code is regenerated. */

#pragma once

#include "CoreUObject.h"
#include "ArticyLocalizerSystem.h"
#include "NanorenoLocalizerSystem.generated.h"

/** Articy Localizer System */
UCLASS(BlueprintType)
class NANORENO_API UNanorenoLocalizerSystem : public UArticyLocalizerSystem
{
	GENERATED_BODY()
	
public:
	void Reload() 
	{
		if (!bListenerSet) {
			FInternationalization::Get().OnCultureChanged().AddUObject(this, &UNanorenoLocalizerSystem::Reload);;
			bListenerSet = true;;
		}
		FString LocaleName = FInternationalization::Get().GetCurrentCulture()->GetName();
		FString LangName = FInternationalization::Get().GetCurrentCulture()->GetTwoLetterISOLanguageName();
FStringTableRegistry::Get().UnregisterStringTable(FName("All_objects"));;
LOCTABLE_FROMFILE_GAME("All_objects", "All_objects", "ArticyContent/Generated/All_objects.csv");;
		bDataLoaded = true;;
	}
};
