// articy Software GmbH & Co. KG
/** This code file was generated by ArticyImporter. Changes to this file will get lost once the code is regenerated. */

#pragma once

#include "CoreUObject.h"
#include "ArticyBaseInclude.h"
#include "NanorenoInterfaces.h"
#include "NanorenoArticyTypes.generated.h"


/** -------------------------------------------------------------------------------- */

UENUM(BlueprintType)
enum
/** UENUM generated form ArticyObjectDef Sex */
class ENanorenoSex : uint8
{
	Male = 0,
	Female = 1,
	Unknown = 2,
};

/** -------------------------------------------------------------------------------- */

UENUM(BlueprintType)
enum
/** UENUM generated form ArticyObjectDef ShapeType */
class ENanorenoShapeType : uint8
{
	Invalid = 0,
	Spot = 1,
	Circle = 2,
	Rectangle = 3,
	Path = 4,
	Polygon = 5,
	Link = 6,
};

/** -------------------------------------------------------------------------------- */

UENUM(BlueprintType)
enum
/** UENUM generated form ArticyObjectDef SelectabilityModes */
class ENanorenoSelectabilityModes : uint8
{
	Unselectable = 0,
	Selectable = 1,
};

/** -------------------------------------------------------------------------------- */

UENUM(BlueprintType)
enum
/** UENUM generated form ArticyObjectDef VisibilityModes */
class ENanorenoVisibilityModes : uint8
{
	Invisible = 0,
	Visible = 1,
};

/** -------------------------------------------------------------------------------- */

UENUM(BlueprintType)
enum
/** UENUM generated form ArticyObjectDef OutlineStyle */
class ENanorenoOutlineStyle : uint8
{
	Solid = 0,
	Dot = 1,
	Dash = 2,
	DashDot = 3,
	DashDotDot = 4,
};

/** -------------------------------------------------------------------------------- */

UENUM(BlueprintType)
enum
/** UENUM generated form ArticyObjectDef PathCaps */
class ENanorenoPathCaps : uint8
{
	ColoredDot = 0,
	None = 1,
	LineArrowHead = 2,
	FilledArrowHead = 3,
	Diamond = 4,
	Square = 5,
	Disc = 6,
};

/** -------------------------------------------------------------------------------- */

/** UCLASS generated from ArticyObjectDef FlowFragment */
UCLASS(BlueprintType)
class NANORENO_API UNanorenoFlowFragment : public UArticyFlowFragment,
 public IArticyObjectWithAttachments,
 public IArticyObjectWithDisplayName,
 public IArticyObjectWithPreviewImage,
 public IArticyObjectWithColor,
 public IArticyObjectWithText,
 public IArticyObjectWithExternalId,
 public IArticyObjectWithPosition,
 public IArticyObjectWithZIndex,
 public IArticyObjectWithSize,
 public IArticyObjectWithShortId
{
	GENERATED_BODY()
	
public:
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Attachments"))
	TArray<FArticyId> Attachments;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DisplayName"))
	FText DisplayName = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="PreviewImage"))
	UArticyPreviewImage* PreviewImage = nullptr;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Color"))
	FLinearColor Color = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Text"))
	FText Text = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ExternalId"))
	FString ExternalId = TEXT("");
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Position"))
	FVector2D Position = FVector2D::ZeroVector;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ZIndex"))
	float ZIndex = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Size"))
	FArticySize Size;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShortId"))
	int32 ShortId = 0;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="InputPins"))
	TArray<UArticyInputPin*> InputPins;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="OutputPins"))
	TArray<UArticyOutputPin*> OutputPins;
};

/** -------------------------------------------------------------------------------- */

/** UCLASS generated from ArticyObjectDef Dialogue */
UCLASS(BlueprintType)
class NANORENO_API UNanorenoDialogue : public UArticyDialogue,
 public IArticyObjectWithAttachments,
 public IArticyObjectWithDisplayName,
 public IArticyObjectWithPreviewImage,
 public IArticyObjectWithColor,
 public IArticyObjectWithText,
 public IArticyObjectWithExternalId,
 public IArticyObjectWithPosition,
 public IArticyObjectWithZIndex,
 public IArticyObjectWithSize,
 public IArticyObjectWithShortId
{
	GENERATED_BODY()
	
public:
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Attachments"))
	TArray<FArticyId> Attachments;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DisplayName"))
	FText DisplayName = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="PreviewImage"))
	UArticyPreviewImage* PreviewImage = nullptr;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Color"))
	FLinearColor Color = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Text"))
	FText Text = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ExternalId"))
	FString ExternalId = TEXT("");
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Position"))
	FVector2D Position = FVector2D::ZeroVector;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ZIndex"))
	float ZIndex = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Size"))
	FArticySize Size;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShortId"))
	int32 ShortId = 0;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="InputPins"))
	TArray<UArticyInputPin*> InputPins;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="OutputPins"))
	TArray<UArticyOutputPin*> OutputPins;
};

/** -------------------------------------------------------------------------------- */

/** UCLASS generated from ArticyObjectDef DialogueFragment */
UCLASS(BlueprintType)
class NANORENO_API UNanorenoDialogueFragment : public UArticyDialogueFragment,
 public IArticyObjectWithMenuText,
 public IArticyObjectWithStageDirections,
 public IArticyObjectWithSpeaker,
 public IArticyObjectWithColor,
 public IArticyObjectWithText,
 public IArticyObjectWithExternalId,
 public IArticyObjectWithPosition,
 public IArticyObjectWithZIndex,
 public IArticyObjectWithSize,
 public IArticyObjectWithShortId
{
	GENERATED_BODY()
	
public:
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="MenuText"))
	FText MenuText = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="StageDirections"))
	FText StageDirections = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Speaker"))
	FArticyId Speaker;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="SplitHeight"))
	float SplitHeight = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Color"))
	FLinearColor Color = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Text"))
	FText Text = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ExternalId"))
	FString ExternalId = TEXT("");
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Position"))
	FVector2D Position = FVector2D::ZeroVector;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ZIndex"))
	float ZIndex = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Size"))
	FArticySize Size;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShortId"))
	int32 ShortId = 0;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="InputPins"))
	TArray<UArticyInputPin*> InputPins;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="OutputPins"))
	TArray<UArticyOutputPin*> OutputPins;
};

/** -------------------------------------------------------------------------------- */

/** UCLASS generated from ArticyObjectDef Hub */
UCLASS(BlueprintType)
class NANORENO_API UNanorenoHub : public UArticyHub,
 public IArticyObjectWithDisplayName,
 public IArticyObjectWithColor,
 public IArticyObjectWithText,
 public IArticyObjectWithExternalId,
 public IArticyObjectWithPosition,
 public IArticyObjectWithZIndex,
 public IArticyObjectWithSize,
 public IArticyObjectWithShortId
{
	GENERATED_BODY()
	
public:
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DisplayName"))
	FText DisplayName = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Color"))
	FLinearColor Color = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Text"))
	FText Text = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ExternalId"))
	FString ExternalId = TEXT("");
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Position"))
	FVector2D Position = FVector2D::ZeroVector;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ZIndex"))
	float ZIndex = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Size"))
	FArticySize Size;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShortId"))
	int32 ShortId = 0;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="InputPins"))
	TArray<UArticyInputPin*> InputPins;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="OutputPins"))
	TArray<UArticyOutputPin*> OutputPins;
};

/** -------------------------------------------------------------------------------- */

/** UCLASS generated from ArticyObjectDef Comment */
UCLASS(BlueprintType)
class NANORENO_API UNanorenoComment : public UArticyComment,
 public IArticyObjectWithColor,
 public IArticyObjectWithText,
 public IArticyObjectWithExternalId,
 public IArticyObjectWithPosition,
 public IArticyObjectWithZIndex,
 public IArticyObjectWithSize,
 public IArticyObjectWithShortId
{
	GENERATED_BODY()
	
public:
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="CreatedBy"))
	FText CreatedBy = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="CreatedOn"))
	FDateTime CreatedOn;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Color"))
	FLinearColor Color = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Text"))
	FText Text = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ExternalId"))
	FString ExternalId = TEXT("");
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Position"))
	FVector2D Position = FVector2D::ZeroVector;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ZIndex"))
	float ZIndex = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Size"))
	FArticySize Size;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShortId"))
	int32 ShortId = 0;
};

/** -------------------------------------------------------------------------------- */

/** UCLASS generated from ArticyObjectDef Jump */
UCLASS(BlueprintType)
class NANORENO_API UNanorenoJump : public UArticyJump,
 public IArticyObjectWithColor,
 public IArticyObjectWithText,
 public IArticyObjectWithExternalId,
 public IArticyObjectWithPosition,
 public IArticyObjectWithZIndex,
 public IArticyObjectWithSize,
 public IArticyObjectWithShortId
{
	GENERATED_BODY()
	
public:
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Color"))
	FLinearColor Color = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Text"))
	FText Text = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ExternalId"))
	FString ExternalId = TEXT("");
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Position"))
	FVector2D Position = FVector2D::ZeroVector;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ZIndex"))
	float ZIndex = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Size"))
	FArticySize Size;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShortId"))
	int32 ShortId = 0;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="InputPins"))
	TArray<UArticyInputPin*> InputPins;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="OutputPins"))
	TArray<UArticyOutputPin*> OutputPins;
};

/** -------------------------------------------------------------------------------- */

/** UCLASS generated from ArticyObjectDef Entity */
UCLASS(BlueprintType)
class NANORENO_API UNanorenoEntity : public UArticyEntity,
 public IArticyObjectWithAttachments,
 public IArticyObjectWithDisplayName,
 public IArticyObjectWithColor,
 public IArticyObjectWithText,
 public IArticyObjectWithExternalId,
 public IArticyObjectWithPosition,
 public IArticyObjectWithZIndex,
 public IArticyObjectWithSize,
 public IArticyObjectWithPreviewImage,
 public IArticyObjectWithShortId
{
	GENERATED_BODY()
	
public:
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Attachments"))
	TArray<FArticyId> Attachments;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DisplayName"))
	FText DisplayName = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Color"))
	FLinearColor Color = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Text"))
	FText Text = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ExternalId"))
	FString ExternalId = TEXT("");
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Position"))
	FVector2D Position = FVector2D::ZeroVector;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ZIndex"))
	float ZIndex = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Size"))
	FArticySize Size;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="PreviewImage"))
	UArticyPreviewImage* PreviewImage = nullptr;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShortId"))
	int32 ShortId = 0;
};

/** -------------------------------------------------------------------------------- */

/** UCLASS generated from Articy Basic Character Properties Feature */
UCLASS(BlueprintType)
class NANORENO_API UNanorenoDefaultBasicCharacterFeatureFeature : public UArticyBaseFeature
{
	GENERATED_BODY()
	
public:
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Age"))
	float Age = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Species"))
	FText Species = FText::GetEmpty();
	UFUNCTION(BlueprintPure, meta=(DisplayName="Get Species (Localized)"))
	FText GetSpecies() { return GetPropertyText(Species); }
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Born in"))
	FText BornIn = FText::GetEmpty();
	UFUNCTION(BlueprintPure, meta=(DisplayName="Get Born In (Localized)"))
	FText GetBornIn() { return GetPropertyText(BornIn); }
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Sex"))
	ENanorenoSex Sex;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Profession"))
	FText Occupation = FText::GetEmpty();
	UFUNCTION(BlueprintPure, meta=(DisplayName="Get Occupation (Localized)"))
	FText GetOccupation() { return GetPropertyText(Occupation); }
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Voice"))
	FText Accent = FText::GetEmpty();
	UFUNCTION(BlueprintPure, meta=(DisplayName="Get Accent (Localized)"))
	FText GetAccent() { return GetPropertyText(Accent); }
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Personality"))
	FText Personality = FText::GetEmpty();
	UFUNCTION(BlueprintPure, meta=(DisplayName="Get Personality (Localized)"))
	FText GetPersonality() { return GetPropertyText(Personality); }
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Appearance"))
	FText Appearance = FText::GetEmpty();
	UFUNCTION(BlueprintPure, meta=(DisplayName="Get Appearance (Localized)"))
	FText GetAppearance() { return GetPropertyText(Appearance); }
};
/** UCLASS generated from ArticyObjectDef DefaultSupportingCharacterTemplate */
UCLASS(BlueprintType)
class NANORENO_API UNanorenoDefaultSupportingCharacterTemplate : public UNanorenoEntity,
 public INanorenoObjectWithDefaultBasicCharacterFeatureFeature
{
	GENERATED_BODY()
	
public:
	
	/** INanorenoObjectWithDefaultBasicCharacterFeatureFeature implementation */
	UNanorenoDefaultBasicCharacterFeatureFeature* GetFeatureDefaultBasicCharacterFeature() const override
	{
		return DefaultBasicCharacterFeature;
	}
	/** Basic Character Properties */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly)
	UNanorenoDefaultBasicCharacterFeatureFeature* DefaultBasicCharacterFeature;
};

/** -------------------------------------------------------------------------------- */

/** UCLASS generated from Articy Extended Character Properties Feature */
UCLASS(BlueprintType)
class NANORENO_API UNanorenoDefaultExtendedCharacterFeatureFeature : public UArticyBaseFeature
{
	GENERATED_BODY()
	
public:
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Goals"))
	FText Motivation = FText::GetEmpty();
	UFUNCTION(BlueprintPure, meta=(DisplayName="Get Motivation (Localized)"))
	FText GetMotivation() { return GetPropertyText(Motivation); }
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Inner Conflict"))
	FText InnerConflict = FText::GetEmpty();
	UFUNCTION(BlueprintPure, meta=(DisplayName="Get Inner Conflict (Localized)"))
	FText GetInnerConflict() { return GetPropertyText(InnerConflict); }
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Skills"))
	FText Skills = FText::GetEmpty();
	UFUNCTION(BlueprintPure, meta=(DisplayName="Get Skills (Localized)"))
	FText GetSkills() { return GetPropertyText(Skills); }
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Weaknesses"))
	FText Fears = FText::GetEmpty();
	UFUNCTION(BlueprintPure, meta=(DisplayName="Get Fears (Localized)"))
	FText GetFears() { return GetPropertyText(Fears); }
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Quirks / Habits"))
	FText Habits = FText::GetEmpty();
	UFUNCTION(BlueprintPure, meta=(DisplayName="Get Habits (Localized)"))
	FText GetHabits() { return GetPropertyText(Habits); }
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Further Details"))
	FText FurtherDetails = FText::GetEmpty();
	UFUNCTION(BlueprintPure, meta=(DisplayName="Get Further Details (Localized)"))
	FText GetFurtherDetails() { return GetPropertyText(FurtherDetails); }
};
/** UCLASS generated from ArticyObjectDef DefaultMainCharacterTemplate */
UCLASS(BlueprintType)
class NANORENO_API UNanorenoDefaultMainCharacterTemplate : public UNanorenoEntity,
 public INanorenoObjectWithDefaultExtendedCharacterFeatureFeature,
 public INanorenoObjectWithDefaultBasicCharacterFeatureFeature
{
	GENERATED_BODY()
	
public:
	
	/** INanorenoObjectWithDefaultExtendedCharacterFeatureFeature implementation */
	UNanorenoDefaultExtendedCharacterFeatureFeature* GetFeatureDefaultExtendedCharacterFeature() const override
	{
		return DefaultExtendedCharacterFeature;
	}
	/** INanorenoObjectWithDefaultBasicCharacterFeatureFeature implementation */
	UNanorenoDefaultBasicCharacterFeatureFeature* GetFeatureDefaultBasicCharacterFeature() const override
	{
		return DefaultBasicCharacterFeature;
	}
	/** Extended Character Properties */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly)
	UNanorenoDefaultExtendedCharacterFeatureFeature* DefaultExtendedCharacterFeature;
	/** Basic Character Properties */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly)
	UNanorenoDefaultBasicCharacterFeatureFeature* DefaultBasicCharacterFeature;
};

/** -------------------------------------------------------------------------------- */

/** UCLASS generated from ArticyObjectDef Location */
UCLASS(BlueprintType)
class NANORENO_API UNanorenoLocation : public UArticyLocation,
 public IArticyObjectWithAttachments,
 public IArticyObjectWithDisplayName,
 public IArticyObjectWithPreviewImage,
 public IArticyObjectWithColor,
 public IArticyObjectWithText,
 public IArticyObjectWithExternalId,
 public IArticyObjectWithPosition,
 public IArticyObjectWithZIndex,
 public IArticyObjectWithSize,
 public IArticyObjectWithShortId
{
	GENERATED_BODY()
	
public:
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Attachments"))
	TArray<FArticyId> Attachments;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DisplayName"))
	FText DisplayName = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="PreviewImage"))
	UArticyPreviewImage* PreviewImage = nullptr;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Color"))
	FLinearColor Color = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Text"))
	FText Text = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ExternalId"))
	FString ExternalId = TEXT("");
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Position"))
	FVector2D Position = FVector2D::ZeroVector;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ZIndex"))
	float ZIndex = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Size"))
	FArticySize Size;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShortId"))
	int32 ShortId = 0;
};

/** -------------------------------------------------------------------------------- */

/** UCLASS generated from ArticyObjectDef Spot */
UCLASS(BlueprintType)
class NANORENO_API UNanorenoSpot : public UArticySpot,
 public IArticyObjectWithDisplayName,
 public IArticyObjectWithColor,
 public IArticyObjectWithText,
 public IArticyObjectWithExternalId,
 public IArticyObjectWithPosition,
 public IArticyObjectWithZIndex,
 public IArticyObjectWithSize,
 public IArticyObjectWithPreviewImage,
 public IArticyObjectWithShortId
{
	GENERATED_BODY()
	
public:
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DisplayName"))
	FText DisplayName = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Color"))
	FLinearColor Color = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Text"))
	FText Text = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ExternalId"))
	FString ExternalId = TEXT("");
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Position"))
	FVector2D Position = FVector2D::ZeroVector;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ZIndex"))
	float ZIndex = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Size"))
	FArticySize Size;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="PreviewImage"))
	UArticyPreviewImage* PreviewImage = nullptr;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShortId"))
	int32 ShortId = 0;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Visibility"))
	ENanorenoVisibilityModes Visibility;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShowDisplayName"))
	bool ShowDisplayName = false;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DisplayNameColor"))
	FLinearColor DisplayNameColor = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DisplayNameSize"))
	int32 DisplayNameSize = 0;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="OutlineColor"))
	FLinearColor OutlineColor = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="OutlineSize"))
	float OutlineSize = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="OutlineStyle"))
	ENanorenoOutlineStyle OutlineStyle;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DropShadow"))
	bool DropShadow = false;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Selectability"))
	ENanorenoSelectabilityModes Selectability;
};

/** -------------------------------------------------------------------------------- */

/** UCLASS generated from ArticyObjectDef Zone */
UCLASS(BlueprintType)
class NANORENO_API UNanorenoZone : public UArticyZone,
 public IArticyObjectWithDisplayName,
 public IArticyObjectWithPreviewImage,
 public IArticyObjectWithVertices,
 public IArticyObjectWithTransform,
 public IArticyObjectWithColor,
 public IArticyObjectWithText,
 public IArticyObjectWithExternalId,
 public IArticyObjectWithZIndex,
 public IArticyObjectWithSize,
 public IArticyObjectWithShortId
{
	GENERATED_BODY()
	
public:
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DisplayName"))
	FText DisplayName = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="PreviewImage"))
	UArticyPreviewImage* PreviewImage = nullptr;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Vertices"))
	TArray<FVector2D> Vertices;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Transform"))
	UArticyTransformation* Transform = nullptr;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShapeType"))
	ENanorenoShapeType ShapeType;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Color"))
	FLinearColor Color = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Text"))
	FText Text = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ExternalId"))
	FString ExternalId = TEXT("");
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ZIndex"))
	float ZIndex = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Size"))
	FArticySize Size;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShortId"))
	int32 ShortId = 0;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Visibility"))
	ENanorenoVisibilityModes Visibility;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="OutlineColor"))
	FLinearColor OutlineColor = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="OutlineSize"))
	float OutlineSize = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="OutlineStyle"))
	ENanorenoOutlineStyle OutlineStyle;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShowDisplayName"))
	bool ShowDisplayName = false;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DisplayNameColor"))
	FLinearColor DisplayNameColor = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DisplayNameSize"))
	int32 DisplayNameSize = 0;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DropShadow"))
	bool DropShadow = false;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Selectability"))
	ENanorenoSelectabilityModes Selectability;
};

/** -------------------------------------------------------------------------------- */

/** UCLASS generated from ArticyObjectDef Path */
UCLASS(BlueprintType)
class NANORENO_API UNanorenoPath : public UArticyPath,
 public IArticyObjectWithDisplayName,
 public IArticyObjectWithPreviewImage,
 public IArticyObjectWithVertices,
 public IArticyObjectWithTransform,
 public IArticyObjectWithColor,
 public IArticyObjectWithText,
 public IArticyObjectWithExternalId,
 public IArticyObjectWithZIndex,
 public IArticyObjectWithSize,
 public IArticyObjectWithShortId
{
	GENERATED_BODY()
	
public:
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DisplayName"))
	FText DisplayName = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="PreviewImage"))
	UArticyPreviewImage* PreviewImage = nullptr;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Vertices"))
	TArray<FVector2D> Vertices;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Transform"))
	UArticyTransformation* Transform = nullptr;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Color"))
	FLinearColor Color = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Text"))
	FText Text = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ExternalId"))
	FString ExternalId = TEXT("");
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ZIndex"))
	float ZIndex = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Size"))
	FArticySize Size;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShortId"))
	int32 ShortId = 0;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Visibility"))
	ENanorenoVisibilityModes Visibility;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Selectability"))
	ENanorenoSelectabilityModes Selectability;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShowDisplayName"))
	bool ShowDisplayName = false;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DisplayNameColor"))
	FLinearColor DisplayNameColor = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DisplayNameSize"))
	int32 DisplayNameSize = 0;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DropShadow"))
	bool DropShadow = false;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="OutlineColor"))
	FLinearColor OutlineColor = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="OutlineSize"))
	float OutlineSize = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="OutlineStyle"))
	ENanorenoOutlineStyle OutlineStyle;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="StartCap"))
	ENanorenoPathCaps StartCap;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="EndCap"))
	ENanorenoPathCaps EndCap;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="LineWidth"))
	float LineWidth = 0.f;
};

/** -------------------------------------------------------------------------------- */

/** UCLASS generated from ArticyObjectDef Link */
UCLASS(BlueprintType)
class NANORENO_API UNanorenoLink : public UArticyLink,
 public IArticyObjectWithColor,
 public IArticyObjectWithText,
 public IArticyObjectWithExternalId,
 public IArticyObjectWithPosition,
 public IArticyObjectWithZIndex,
 public IArticyObjectWithSize,
 public IArticyObjectWithTarget,
 public IArticyObjectWithShortId
{
	GENERATED_BODY()
	
public:
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Color"))
	FLinearColor Color = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Text"))
	FText Text = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ExternalId"))
	FString ExternalId = TEXT("");
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Position"))
	FVector2D Position = FVector2D::ZeroVector;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ZIndex"))
	float ZIndex = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Size"))
	FArticySize Size;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Target"))
	FArticyId Target;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShortId"))
	int32 ShortId = 0;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Visibility"))
	ENanorenoVisibilityModes Visibility;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShowDisplayName"))
	bool ShowDisplayName = false;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DisplayNameColor"))
	FLinearColor DisplayNameColor = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DisplayNameSize"))
	int32 DisplayNameSize = 0;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Selectability"))
	ENanorenoSelectabilityModes Selectability;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DropShadow"))
	bool DropShadow = false;
};

/** -------------------------------------------------------------------------------- */

/** UCLASS generated from ArticyObjectDef Asset */
UCLASS(BlueprintType)
class NANORENO_API UNanorenoAsset : public UArticyAsset,
 public IArticyObjectWithDisplayName,
 public IArticyObjectWithPreviewImage,
 public IArticyObjectWithColor,
 public IArticyObjectWithText,
 public IArticyObjectWithExternalId,
 public IArticyObjectWithPosition,
 public IArticyObjectWithZIndex,
 public IArticyObjectWithSize,
 public IArticyObjectWithShortId
{
	GENERATED_BODY()
	
public:
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DisplayName"))
	FText DisplayName = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Filename"))
	FText Filename = FText::GetEmpty();
	UFUNCTION(BlueprintPure, meta=(DisplayName="Get Filename (Localized)"))
	FText GetFilename() { return GetPropertyText(Filename); }
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="OriginalSource"))
	FText OriginalSource = FText::GetEmpty();
	UFUNCTION(BlueprintPure, meta=(DisplayName="Get Original Source (Localized)"))
	FText GetOriginalSource() { return GetPropertyText(OriginalSource); }
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="PreviewImage"))
	UArticyPreviewImage* PreviewImage = nullptr;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Color"))
	FLinearColor Color = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Text"))
	FText Text = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ExternalId"))
	FString ExternalId = TEXT("");
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Position"))
	FVector2D Position = FVector2D::ZeroVector;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ZIndex"))
	float ZIndex = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Size"))
	FArticySize Size;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShortId"))
	int32 ShortId = 0;
};

/** -------------------------------------------------------------------------------- */

/** UCLASS generated from ArticyObjectDef Condition */
UCLASS(BlueprintType)
class NANORENO_API UNanorenoCondition : public UArticyCondition,
 public IArticyObjectWithDisplayName,
 public IArticyObjectWithText,
 public IArticyObjectWithExternalId,
 public IArticyObjectWithPosition,
 public IArticyObjectWithZIndex,
 public IArticyObjectWithSize,
 public IArticyObjectWithShortId,
 public IArticyObjectWithColor
{
	GENERATED_BODY()
	
public:
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DisplayName"))
	FText DisplayName = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Text"))
	FText Text = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ExternalId"))
	FString ExternalId = TEXT("");
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Position"))
	FVector2D Position = FVector2D::ZeroVector;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ZIndex"))
	float ZIndex = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Size"))
	FArticySize Size;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShortId"))
	int32 ShortId = 0;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Expression"))
	UArticyScriptCondition* Expression = nullptr;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Color"))
	FLinearColor Color = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="InputPins"))
	TArray<UArticyInputPin*> InputPins;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="OutputPins"))
	TArray<UArticyOutputPin*> OutputPins;
};

/** -------------------------------------------------------------------------------- */

/** UCLASS generated from ArticyObjectDef Instruction */
UCLASS(BlueprintType)
class NANORENO_API UNanorenoInstruction : public UArticyInstruction,
 public IArticyObjectWithDisplayName,
 public IArticyObjectWithText,
 public IArticyObjectWithExternalId,
 public IArticyObjectWithPosition,
 public IArticyObjectWithZIndex,
 public IArticyObjectWithSize,
 public IArticyObjectWithShortId,
 public IArticyObjectWithColor
{
	GENERATED_BODY()
	
public:
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DisplayName"))
	FText DisplayName = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Text"))
	FText Text = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ExternalId"))
	FString ExternalId = TEXT("");
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Position"))
	FVector2D Position = FVector2D::ZeroVector;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ZIndex"))
	float ZIndex = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Size"))
	FArticySize Size;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShortId"))
	int32 ShortId = 0;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Expression"))
	UArticyScriptInstruction* Expression = nullptr;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Color"))
	FLinearColor Color = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="InputPins"))
	TArray<UArticyInputPin*> InputPins;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="OutputPins"))
	TArray<UArticyOutputPin*> OutputPins;
};

/** -------------------------------------------------------------------------------- */

/** UCLASS generated from ArticyObjectDef LocationText */
UCLASS(BlueprintType)
class NANORENO_API UNanorenoLocationText : public UArticyLocationText,
 public IArticyObjectWithDisplayName,
 public IArticyObjectWithPreviewImage,
 public IArticyObjectWithVertices,
 public IArticyObjectWithTransform,
 public IArticyObjectWithColor,
 public IArticyObjectWithText,
 public IArticyObjectWithExternalId,
 public IArticyObjectWithZIndex,
 public IArticyObjectWithSize,
 public IArticyObjectWithShortId
{
	GENERATED_BODY()
	
public:
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DisplayName"))
	FText DisplayName = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="PreviewImage"))
	UArticyPreviewImage* PreviewImage = nullptr;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Anchors"))
	TArray<FArticyLocationAnchor> Anchors;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Vertices"))
	TArray<FVector2D> Vertices;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Transform"))
	UArticyTransformation* Transform = nullptr;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShapeType"))
	ENanorenoShapeType ShapeType;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Color"))
	FLinearColor Color = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Text"))
	FText Text = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ExternalId"))
	FString ExternalId = TEXT("");
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ZIndex"))
	float ZIndex = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Size"))
	FArticySize Size;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShortId"))
	int32 ShortId = 0;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Visibility"))
	ENanorenoVisibilityModes Visibility;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="OutlineColor"))
	FLinearColor OutlineColor = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="OutlineSize"))
	float OutlineSize = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="OutlineStyle"))
	ENanorenoOutlineStyle OutlineStyle;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Selectability"))
	ENanorenoSelectabilityModes Selectability;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ForcedWidth"))
	float ForcedWidth = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ForcedHeight"))
	float ForcedHeight = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DropShadow"))
	bool DropShadow = false;
};

/** -------------------------------------------------------------------------------- */

/** UCLASS generated from ArticyObjectDef LocationImage */
UCLASS(BlueprintType)
class NANORENO_API UNanorenoLocationImage : public UArticyLocationImage,
 public IArticyObjectWithDisplayName,
 public IArticyObjectWithPreviewImage,
 public IArticyObjectWithVertices,
 public IArticyObjectWithTransform,
 public IArticyObjectWithColor,
 public IArticyObjectWithText,
 public IArticyObjectWithExternalId,
 public IArticyObjectWithZIndex,
 public IArticyObjectWithSize,
 public IArticyObjectWithShortId
{
	GENERATED_BODY()
	
public:
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DisplayName"))
	FText DisplayName = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="PreviewImage"))
	UArticyPreviewImage* PreviewImage = nullptr;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Anchors"))
	TArray<FArticyLocationAnchor> Anchors;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Vertices"))
	TArray<FVector2D> Vertices;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Transform"))
	UArticyTransformation* Transform = nullptr;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShapeType"))
	ENanorenoShapeType ShapeType;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Color"))
	FLinearColor Color = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Text"))
	FText Text = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ExternalId"))
	FString ExternalId = TEXT("");
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ZIndex"))
	float ZIndex = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Size"))
	FArticySize Size;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShortId"))
	int32 ShortId = 0;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Visibility"))
	ENanorenoVisibilityModes Visibility;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="OutlineColor"))
	FLinearColor OutlineColor = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="OutlineSize"))
	float OutlineSize = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="OutlineStyle"))
	ENanorenoOutlineStyle OutlineStyle;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Selectability"))
	ENanorenoSelectabilityModes Selectability;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DropShadow"))
	bool DropShadow = false;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ClipRect"))
	FArticyRect ClipRect;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ImageOpacity"))
	float ImageOpacity = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ImageAsset"))
	FArticyId ImageAsset;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="CachedImageWidth"))
	int32 CachedImageWidth = 0;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="CachedImageHeight"))
	int32 CachedImageHeight = 0;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShowDisplayName"))
	bool ShowDisplayName = false;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DisplayNameColor"))
	FLinearColor DisplayNameColor = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DisplayNameSize"))
	int32 DisplayNameSize = 0;
};

/** -------------------------------------------------------------------------------- */

/** UCLASS generated from ArticyObjectDef Document */
UCLASS(BlueprintType)
class NANORENO_API UNanorenoDocument : public UArticyDocument,
 public IArticyObjectWithDisplayName,
 public IArticyObjectWithColor,
 public IArticyObjectWithText,
 public IArticyObjectWithExternalId,
 public IArticyObjectWithPosition,
 public IArticyObjectWithZIndex,
 public IArticyObjectWithSize,
 public IArticyObjectWithShortId
{
	GENERATED_BODY()
	
public:
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DisplayName"))
	FText DisplayName = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Color"))
	FLinearColor Color = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Text"))
	FText Text = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ExternalId"))
	FString ExternalId = TEXT("");
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Position"))
	FVector2D Position = FVector2D::ZeroVector;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ZIndex"))
	float ZIndex = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Size"))
	FArticySize Size;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShortId"))
	int32 ShortId = 0;
};

/** -------------------------------------------------------------------------------- */

/** UCLASS generated from ArticyObjectDef TextObject */
UCLASS(BlueprintType)
class NANORENO_API UNanorenoTextObject : public UArticyTextObject,
 public IArticyObjectWithDisplayName,
 public IArticyObjectWithAttachments,
 public IArticyObjectWithPreviewImage,
 public IArticyObjectWithColor,
 public IArticyObjectWithText,
 public IArticyObjectWithExternalId,
 public IArticyObjectWithPosition,
 public IArticyObjectWithZIndex,
 public IArticyObjectWithSize,
 public IArticyObjectWithShortId
{
	GENERATED_BODY()
	
public:
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DisplayName"))
	FText DisplayName = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Attachments"))
	TArray<FArticyId> Attachments;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="PreviewImage"))
	UArticyPreviewImage* PreviewImage = nullptr;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Color"))
	FLinearColor Color = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Text"))
	FText Text = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ExternalId"))
	FString ExternalId = TEXT("");
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Position"))
	FVector2D Position = FVector2D::ZeroVector;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ZIndex"))
	float ZIndex = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Size"))
	FArticySize Size;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShortId"))
	int32 ShortId = 0;
};

/** -------------------------------------------------------------------------------- */

/** UCLASS generated from ArticyObjectDef UserFolder */
UCLASS(BlueprintType)
class NANORENO_API UNanorenoUserFolder : public UArticyUserFolder,
 public IArticyObjectWithDisplayName,
 public IArticyObjectWithExternalId,
 public IArticyObjectWithShortId,
 public IArticyObjectWithZIndex
{
	GENERATED_BODY()
	
public:
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DisplayName"))
	FText DisplayName = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ExternalId"))
	FString ExternalId = TEXT("");
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShortId"))
	int32 ShortId = 0;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ZIndex"))
	float ZIndex = 0.f;
};
