// articy Software GmbH & Co. KG
/** This code file was generated by ArticyImporter. Changes to this file will get lost once the code is regenerated. */

#pragma once

#include "CoreUObject.h"
#include "ArticyGlobalVariables.h"
#include "NanorenoGlobalVariables.generated.h"
#if !((defined(PLATFORM_PS4) && PLATFORM_PS4) || (defined(PLATFORM_PS5) && PLATFORM_PS5))
#pragma warning(push)
#pragma warning(disable: 4883) //<disable "optimization cannot be applied due to function size" compile error.
#endif

UCLASS(BlueprintType)
class NANORENO_API UNanorenoGameStateVariables : public UArticyBaseVariableSet
{
	GENERATED_BODY()
	
public:
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="GameState")
	UArticyBool* BooksDelivered = nullptr;
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="GameState")
	UArticyBool* DeliverMailWOBreakfast = nullptr;
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="GameState")
	UArticyBool* InquireAboutBooks = nullptr;
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="GameState")
	UArticyBool* OpenedMailbox = nullptr;
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="GameState")
	UArticyBool* LookedAroundMailbox = nullptr;
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="GameState")
	UArticyBool* TookMushlingMail = nullptr;
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="GameState")
	UArticyBool* TookMushlingMail2 = nullptr;
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="GameState")
	UArticyBool* TookMushlingMail3 = nullptr;
	
	 UNanorenoGameStateVariables() 
	{
		BooksDelivered = CreateDefaultSubobject<UArticyBool>("BooksDelivered");
		DeliverMailWOBreakfast = CreateDefaultSubobject<UArticyBool>("DeliverMailWOBreakfast");
		InquireAboutBooks = CreateDefaultSubobject<UArticyBool>("InquireAboutBooks");
		OpenedMailbox = CreateDefaultSubobject<UArticyBool>("OpenedMailbox");
		LookedAroundMailbox = CreateDefaultSubobject<UArticyBool>("LookedAroundMailbox");
		TookMushlingMail = CreateDefaultSubobject<UArticyBool>("TookMushlingMail");
		TookMushlingMail2 = CreateDefaultSubobject<UArticyBool>("TookMushlingMail2");
		TookMushlingMail3 = CreateDefaultSubobject<UArticyBool>("TookMushlingMail3");
	}
	
	void Init(UArticyGlobalVariables* const Store) 
	{
		/** initialize the variables */
		BooksDelivered->Init<UArticyBool>(this, Store, TEXT("GameState.BooksDelivered"), false);
		this->Variables.Add(BooksDelivered);
		DeliverMailWOBreakfast->Init<UArticyBool>(this, Store, TEXT("GameState.DeliverMailWOBreakfast"), false);
		this->Variables.Add(DeliverMailWOBreakfast);
		InquireAboutBooks->Init<UArticyBool>(this, Store, TEXT("GameState.InquireAboutBooks"), false);
		this->Variables.Add(InquireAboutBooks);
		OpenedMailbox->Init<UArticyBool>(this, Store, TEXT("GameState.OpenedMailbox"), false);
		this->Variables.Add(OpenedMailbox);
		LookedAroundMailbox->Init<UArticyBool>(this, Store, TEXT("GameState.LookedAroundMailbox"), false);
		this->Variables.Add(LookedAroundMailbox);
		TookMushlingMail->Init<UArticyBool>(this, Store, TEXT("GameState.TookMushlingMail"), false);
		this->Variables.Add(TookMushlingMail);
		TookMushlingMail2->Init<UArticyBool>(this, Store, TEXT("GameState.TookMushlingMail2"), false);
		this->Variables.Add(TookMushlingMail2);
		TookMushlingMail3->Init<UArticyBool>(this, Store, TEXT("GameState.TookMushlingMail3"), false);
		this->Variables.Add(TookMushlingMail3);
	}
};

/** Global Articy Variables */
UCLASS(BlueprintType)
class NANORENO_API UNanorenoGlobalVariables : public UArticyGlobalVariables
{
	GENERATED_BODY()
	
public:
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="GameState")
	UNanorenoGameStateVariables* GameState = nullptr;
	
	 UNanorenoGlobalVariables() 
	{
		/** create the namespaces */
		GameState = CreateDefaultSubobject<UNanorenoGameStateVariables>("GameState");
		
		Init();
	}
	
	void Init() 
	{
		/** initialize the namespaces */
		GameState->Init(this);
		this->VariableSets.Add(GameState);
	}
	
	/** Get the default GlobalVariables (a copy of the asset). */
	UFUNCTION(BlueprintPure, Category="ArticyGlobalVariables", meta=(HidePin="WorldContext", DefaultToSelf="WorldContext", DisplayName="GetArticyGV", keywords="global variables"))
	static UNanorenoGlobalVariables* GetDefault(const UObject* WorldContext) 
	{
		return static_cast<UNanorenoGlobalVariables*>(UArticyGlobalVariables::GetDefault(WorldContext));
	}
};
#if !((defined(PLATFORM_PS4) && PLATFORM_PS4) || (defined(PLATFORM_PS5) && PLATFORM_PS5))
#pragma warning(pop)
#endif
