// articy Software GmbH & Co. KG
/** This code file was generated by ArticyImporter. Changes to this file will get lost once the code is regenerated. */

#pragma once

#include "CoreUObject.h"
#include "NanorenoInterfaces.generated.h"


/** UNINTERFACE generated from Articy Basic Character Properties Feature */
UINTERFACE(MinimalAPI, BlueprintType, Category="Nanoreno Feature Interfaces", meta=(CannotImplementInterfaceInBlueprint))
class UNanorenoObjectWithDefaultBasicCharacterFeatureFeature : public UInterface { GENERATED_BODY() };
class INanorenoObjectWithDefaultBasicCharacterFeatureFeature
{
	GENERATED_BODY()
	
public:
	
	UFUNCTION(BlueprintCallable)
	virtual class UNanorenoDefaultBasicCharacterFeatureFeature* GetFeatureDefaultBasicCharacterFeature() const
	{
		return nullptr;
	}
};

/** UNINTERFACE generated from Articy Extended Character Properties Feature */
UINTERFACE(MinimalAPI, BlueprintType, Category="Nanoreno Feature Interfaces", meta=(CannotImplementInterfaceInBlueprint))
class UNanorenoObjectWithDefaultExtendedCharacterFeatureFeature : public UInterface { GENERATED_BODY() };
class INanorenoObjectWithDefaultExtendedCharacterFeatureFeature
{
	GENERATED_BODY()
	
public:
	
	UFUNCTION(BlueprintCallable)
	virtual class UNanorenoDefaultExtendedCharacterFeatureFeature* GetFeatureDefaultExtendedCharacterFeature() const
	{
		return nullptr;
	}
};
